### ISSUE TITLE
code-groups not working correctly in this theme

### ISSUE THREAD

**Issue by thebootable** [CachetHQ/Docs#3]
## short description
It seems that the [Vitepress Code Groups](https://vitepress.dev/guide/markdown#code-groups) are not working as intended.
I assume it's a problem in the theme.

## environment
I'm using firefox and chrome on ubuntu. The page was created with the dev-environement.

## observed behavior
When using a `::: code-group` block in a markdown-file, the contents get resolved to seperate blocks and show a radiobutton-menu on the top that has no effect on the look of the page itself.

### Screenshot
![screenshot_code-group](https://github.com/cachethq/docs/assets/40902295/4da6082e-1360-4ece-bb63-69b705a83776)

### used code
I used the sample code from vitepress:
~~~md
::: code-group

```js [config.js]
/**
 * @type {import('vitepress').UserConfig}
 */
const config = {
  // ...
}

export default config
```

```ts [config.ts]
import type { UserConfig } from 'vitepress'

const config: UserConfig = {
  // ...
}


export default config
```

:::
~~~

## expected behavior
I'd expect to have a combined code-block with a menu on the top to choose between the code-blocks. See also [Vitepress documentation for Code Groups](https://vitepress.dev/guide/markdown#code-groups).
Because the basic functionality seems to work and it looks more like a displayed problem, I assume it's a problem with the theme.
I have no error-messages or logs that would indicate otherwise

Personally, I think code-groups would be a good fit for documentation. Of course there are other styling options but it's a neat feature and should be supported by the theme.

**Comment by jbrooksuk** [comment]
I agree this would be cool. Please can you open an issue on the [pilgrim-theme](https://github.com/davidhemphill/pilgrim-theme) repo.

**Comment by thebootable** [comment]
ah yeah, was not sure if it really is an issue with the theme.
I opened an issue, see https://github.com/davidhemphill/pilgrim-theme/issues/3
