### ISSUE TITLE
Api Docs are missing the content expected by the endpoint

### ISSUE THREAD

**Issue by MTRNord** [CachetHQ/Docs#7]
It would be nice if the api docs also mention which data is possible on each endpoint. Currently, this (I guess) has to be derived from testing it via the UI or looking into the source. Nicer would be to just look at the docs page :)

**Comment by jbrooksuk** [comment]
Absolutely! The API docs will actually be generated automatically with Scribe in the near future.

**Comment by jbrooksuk** [comment]
@MTRNord here you go: https://docs.cachethq.io/api-reference/introduction
